--create a product table having fields like
--prod_id,prod_name,prod_desc,price

create table product(
prod_id SERIAL PRIMARY KEY,
prod_name VARCHAR(10),
prod_desc VARCHAR(20),
price NUMERIC(5,2)
);

-- select * from product

-- ALTER TABLE product
-- ADD PRIMARY KEY (product_id);

-- drop table product;

select * from product;

-- alter table product
-- add column prod_category VARCHAR(10);

-- insert into product(prod_name, prod_desc, price) values('Meat','Edible stuff',500.20);

-- update product
-- set prod_category='Food'
-- where prod_id=1;
insert into product(prod_name, prod_desc, price) values('Fish','Edible stuff',400.00,'Food');
insert into product(prod_name, prod_desc, price) values('Phone','Mobile Smart Phone',500.20,'Electronics');
insert into product(prod_name, prod_desc, price) values('Lap','Edible stuff',500.20);


--index

create index idx_prodname on product(prod_name)
select * from product


--DAY 2

--1. Fetch order details along with product name and price

select orders.*,product.prod_name,product.price
from product INNER JOIN orders
on product.prod_id=orders.prod_id;


--2. Total revenue generated by each product

select sum(price) as tot_rev,prod_name
from product inner join orders
on product.prod_id=orders.prod_id
group by orders.prod_id,prod_name;


--3. Products that have never been ordered

select prod_name,product.prod_id
from product left outer join orders
on product.prod_id=orders.prod_id
where orders.prod_id is NULL;

--4. Products with more repeat orders than new orders

select prod_name,orders.prod_id
from product inner join orders
on product.prod_id=orders.prod_id
group by orders.prod_id,prod_name
having count(*)>1

--5. Top 3 products based on number of orders

select orders.prod_id,prod_name,count(*)
from product inner join orders
on product.prod_id=orders.prod_id
group by orders.prod_id,prod_name
order by count(*) desc
limit 3;

--6. Total revenue from 'new' and 'repeat' orders separately

select sum(price) as tot_rev
from product inner join orders
on product.prod_id=orders.prod_id
group by orders.prod_id
having count(*)>1;

select * from orders;

--7.Month-wise total revenue

select TO_CHAR(ord_date, 'YYYY-MM') as month, sum(price) as total_rev
from product inner join orders 
on product.prod_id = orders.prod_id
group by TO_CHAR(ord_date, 'YYYY-MM')
order by month;


--PL PG SQL--

CREATE OR REPLACE FUNCTION  add_numbers(a INT,b INT)
RETURNS INT
AS $$
BEGIN
	RETURN a+b;
END;
$$ LANGUAGE plpgsql;

select add_numbers(100,50);

-- create a function that takes the product name as input and returns the price

CREATE OR REPLACE FUNCTION show_price (prd_name VARCHAR)
RETURNS INT
AS $$
DECLARE prod_price int;
BEGIN
	select price into prod_price
	from product where prod_name=prd_name;
	return prod_price;
END;
$$ LANGUAGE plpgsql;

select show_price('Meat')

-- create a function that takes column input and returns the table

CREATE OR REPLACE FUNCTION show_values(prd_name VARCHAR)
RETURNS TABLE(id INT, name VARCHAR(20))
AS $$
BEGIN
    RETURN QUERY 
    SELECT prod_id, prod_name
    FROM product
    WHERE prod_name = prd_name;
END;
$$ LANGUAGE plpgsql;

select show_values('Fish')

--write a procedure that takes product fields as input and add a new row in product table

CREATE OR REPLACE PROCEDURE addRecords(prd_id INT,prd_name VARCHAR,prd_desc VARCHAR,prd_price NUMERIC,prd_category VARCHAR)
AS $$
BEGIN
	INSERT INTO product values(prd_id,prd_name,prd_desc,prd_price,prd_category);
END;
$$ LANGUAGE plpgsql;

CALL addRecords(15,'Pizza','Cheesy Delight',100,'Food');

select * from product

--write a procedure that takes prod id and discounted price as input and apply discounted price in all given prod ids

CREATE OR REPLACE PROCEDURE applyDiscount(prd_id INT,dis_price INT)
AS $$
BEGIN
	UPDATE product 
	SET price=dis_price
	WHERE prd_id=prod_id;
END;
$$ LANGUAGE plpgsql;

CALL applyDiscount(10,30)
select * from product


-- Create accounts table having id, name and balance field
-- Create account_audit table having account_id, old_balance, new_balance, changed_on fields

create table accounts(id SERIAL PRIMARY KEY,name VARCHAR(100),balance numeric);
create table account_audit(
account_id int,
old_balance numeric,
new_balance numeric,
changed_on timestamp DEFAULT CURRENT_TIMESTAMP
);

--Trigger Function
CREATE OR REPLACE FUNCTION log_balance_update()
RETURNS TRIGGER
AS $$
BEGIN
	INSERT INTO account_audit(account_id,old_balance,new_balance)
	VALUES (OLD.id,OLD.balance,NEW.balance);

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

------Trigger------
CREATE TRIGGER balance_update_trigger
AFTER UPDATE ON accounts
FOR EACH ROW
WHEN(OLD.balance IS DISTINCT FROM NEW.balance)
EXECUTE FUNCTION log_balance_update();


INSERT INTO accounts(name,balance) values('RAJA',1000)
INSERT INTO accounts(name,balance) values('HAMZA',2000)

select * from accounts;
select * from account_audit;

update accounts set balance = 15000 where id = 1;

-----Query Execution Plan-----
explain insert into accounts(name,balance) values('ABBAS',500);